services:
  web:
    env_file:
      - secrets.env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
  monitor:
    env_file:
      - secrets.env
    build:
      context: .
    volumes:
      - .:/app
    command: python -u -m monitor.mqtt_daemon
  redis:
    image: redis
  celery:
    env_file:
      - secrets.env
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A web.tasks worker -l info
  celery-beat:
    env_file:
      - secrets.env
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A web.tasks beat -l info