apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
      component: celery
  template:
    metadata:
      labels:
        app: green
        component: celery
    spec:
      containers:
        - name: celery
          image: ealmuina/green:latest
          envFrom:
            - secretRef:
                name: green-secrets
          command: [ "celery", "-A", "web.tasks", "worker", "-l", "info" ]
