apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
      component: redis
  template:
    metadata:
      labels:
        app: green
        component: redis
    spec:
      containers:
        - name: redis
          image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: green-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
  selector:
    app: green
    component: redis