apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ealmuina/green:latest
          envFrom:
            - secretRef:
                name: green-secrets
          command: [ "./run_web.sh" ]

---

apiVersion: v1
kind: Service
metadata:
  name: green-web
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: web