# Generated by Django 4.0.4 on 2022-05-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.IntegerField(choices=[(0, 'Full'), (1, 'Pump'), (2, 'Valve')])),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='firmware')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(max_length=20, unique=True)),
                ('node_type', models.IntegerField(choices=[(0, 'Full'), (1, 'Pump'), (2, 'Valve')])),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('min_moisture', models.IntegerField(blank=True, null=True)),
                ('max_moisture', models.IntegerField(blank=True, null=True)),
                ('max_open_time', models.IntegerField(default=30)),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.node')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='web.node')),
            ],
        ),
    ]
