# Generated by Django 4.0.4 on 2022-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(upload_to='media/firmware'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.IntegerField(unique=True),
        ),
    ]
