# Generated by Django 4.0.4 on 2022-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_alter_firmware_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(upload_to='firmware'),
        ),
    ]
