# Generated by Django 4.0.4 on 2022-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_alter_firmware_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='max_open_time',
            field=models.IntegerField(default=10000),
        ),
    ]
