name: deploy
on:
  push:
    branches:
      - main
jobs:
  #  run-tests:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: ./.github/set-environment
  #        with:
  #          secret_key: ${{ secrets.SECRET_KEY }}
  #
  #      - name: Build Docker image
  #        run: docker-compose build
  #
  #      - name: Apply migrations to test DB
  #        run: docker-compose run celery python manage.py migrate
  #
  #      - name: Execute tests
  #        run: docker-compose -f docker-compose.dev.yml run -e "RAILS_ENV=test" web rake test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/set-environment
        with:
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ealmuina/green:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/set-environment
        with:
          secret_key: ${{ secrets.SECRET_KEY }}

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd green
            
            # Pull new code
            git stash
            git checkout main
            git pull
            
            # Create .env file
            touch secrets.env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} > secrets.env
            echo MQTT_BROKER_HOST=${{ secrets.MQTT_BROKER_HOST }} >> secrets.env
            echo MQTT_BROKER_PORT=${{ secrets.MQTT_BROKER_PORT }} >> secrets.env
            echo FIRMWARE_PASSWORD=${{ secrets.FIRMWARE_PASSWORD }} >> secrets.env
            
            # Create k8s secrets
            kubectl create secret generic green-secrets --from-env-file=secrets.env
            
            # Build containers
            for file in manifests/*; do
              kubectl apply -f $file
            done
            
            # Delete old pods
            kubectl delete pods -l app=green
